### ISSUE TITLE
decoded output is corrupt?

### ISSUE THREAD

**Issue by famaik** [fraunhoferhhi/vvdec#111]
Hi,

I'm new to vvc, so there might be a basic mistake here. But the decoded output looks very wrong (grayscale instead of color, and continuously moving from left to right)

The raw input (raw.mkv, zipped to raw.zip to allow file attachment) is a 720p 30 second 10-bit video , with frame rate of 23.99fps

I encode it using vvencapp using this command line:
`ffmpeg -i t.mkv -pix_fmt yuv420p -s 640x360 -f yuv4mpegpipe - |vvencapp -i - -s 640x360 -r 24 -v 0  -o tmp.x266`

The encoded tmp.x266 
[encoded.zip](https://github.com/fraunhoferhhi/vvdec/files/9471655/encoded.zip)
 stream is then decoded, and piped to mpv for viewing, where the output looks corrupt
`vvdecapp -b tmp.x266 --y4m -o - |mpv -`

For purpose of attachment, I've encoded output to decoded.mp4 (file is attached below) as follows:
`vvdecapp -b tmp.x266 --y4m -o - |ffmpeg -i - -c:v h264 decoded.mp4`

https://user-images.githubusercontent.com/111527157/187965599-8544aab8-4ff4-48aa-86e0-e332afa94760.mp4

I guess there's some mistake here somewhere. Help would be appreciated. Thanks

[raw.zip](https://github.com/fraunhoferhhi/vvdec/files/9471644/raw.zip)

**Comment by adamjw24** [comment]
You are piping a y4m to the encoder, but not telling it. Please add `--y4m` to the cmd (i.e. `ffmpeg .... -f yuv4mpegpipe | vvenc -i - --y4m ...`. On the decoder side its all good.

**Comment by famaik** [comment]
thank you. everything works ok now. closing this
