### ISSUE TITLE
Decoding vvc file failed by using vvdec ,but it successed by using VTM

### ISSUE THREAD

**Issue by whhwhhwhh** [fraunhoferhhi/vvdec#112]
Hello,
I have a  VVC  file ，which can be decoded successfully by VTM, but when I use  the vvdec application to decode it ,it fails. It gave me the following error:
vvdecapp [error]: decoding failed:  (decoder requires restart) detail: caught unknown exception
ERROR: In function "void __cdecl vvdec::InterPrediction::xPredInterUni(const struct vvdec::CodingUnit &,const enum vvdec::RefPicList &,struct vvdec::UnitBuf<short> &,const bool &,const bool &,const bool,const bool)" in D:\vvdec\source\Lib\CommonLib\InterPrediction.cpp:641: xPredInterUni missing ref pic
ERROR CONDITION: !refPic
Please give me your email，I can send the vvc file to you. Thanks！

**Comment by K-os** [comment]
Can you please upload your bitstream here: https://datacloud.hhi.fraunhofer.de/s/jtmEBpia5XoPXe9

**Comment by whhwhhwhh** [comment]
> Can you please upload your bitstream here: https://datacloud.hhi.fraunhofer.de/s/jtmEBpia5XoPXe9

ok

**Comment by K-os** [comment]
Thanks. We will have a look at it.
