### ISSUE TITLE
multithreading stuck

### ISSUE THREAD

**Issue by whhwhhwhh** [fraunhoferhhi/vvdec#117]
When I use vvdec to decode my bitstream on the linux server, if I don't add the “-t”  parameter , it will get stuck. But if I set -t 64  ,it run successfully.

**Comment by adamjw24** [comment]
How many cores does your server have?

But jokes aside, there might be a bug somewhere if the number of threads is too high, and it is always per default set to the number of available threads. We will probably introduce a cap on the number of default threads to something we know works, which would resolve your problem. Thanks for reporting. Might take until IBC to fix.

**Comment by adamjw24** [comment]
Just to make. Does the app report the header? (i.e. the line with vvdec name, version, compiler, cpu flags and threads)

How many used threads are reported? If the line is not visible, the problem would with the detection of the number of threads, which is a different problem.

**Comment by K-os** [comment]
@whhwhhwhh can you please test with the current master revision if the problem is fixed for you?

**Comment by whhwhhwhh** [comment]
> @whhwhhwhh can you please test with the current master revision if the problem is fixed for you?
yes，it fixed. Thank you !
