### ISSUE TITLE
Failed playing with v2.3.0 on a test file

### ISSUE THREAD

**Issue by xav1vfw** [fraunhoferhhi/vvdec#181]
All of my test files work with v.2.2.0 release,
but - it seems - one of them doesn't work with v2.3.0,
using VVdec by FFmpeg.
The problematic file can be downloaded from here:
https://www.ligh.de/tmp/foreman_cif_pal.266.mp4
https://code.videolan.org/videolan/vlc/-/issues/27055

**Comment by K-os** [comment]
I'll have a look. Thanks for the report.

**Comment by K-os** [comment]
Good catch! A conformance check was placed in the wrong position in the code. The fix should probably be merged soon.

Is the linked VLC issue in your report related in any way?

**Comment by xav1vfw** [comment]
I've tested the modified code (this patch on the git head), all of my test files work with it now. Thnx
The VLC link is only for an alternative download for the same MP4 file, otherwise it's not related to this bug.
