### ISSUE TITLE
Compilation error if ENABLE_FILM_GRAIN is not defined.

### ISSUE THREAD

**Issue by v0lt** [fraunhoferhhi/vvdec#187]
Compilation error if `ENABLE_FILM_GRAIN` is not defined.
The problem occurs in this line when checking the condition in the last parameter of the function.
`ret = xCreateFrame( cFrame, cPicBuf, uiWidth, uiHeight, bitDepths, bCreateStorage, m_filmGrainCharacteristicsState != FgcNone );`

**Comment by K-os** [comment]
Oh, yes. Somebody already created a PR. #188

**Comment by adamjw24** [comment]
Thanks!
