### ISSUE TITLE
15360x8640 resolution incorrectly displayed as 45495x45495 in ffmpeg

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [fraunhoferhhi/vvdec#189]
Hello VVDEC developers, I used to use FFmpeg-VVC compiled by Mr. Martin Eesmaa to compress videos with 16k resolution, but I found a bug, I had given feedback to Martin Eesmaa (https://github.com/MartinEesmaa/VVCEasy/issues/52) and he tested it for me, Only MediaInfo and FFmpeg VVC native decoder reports fine. he thinks the problem is with vvdec, so I would like to know your opinion:
When typing `. \ffprobe_vvceasy -i 1.vvc` command, at this point what it shows is normal; 
<img width="863" alt="屏幕截图 2024-07-01 220144" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/71fe29ce-70e7-4f29-b337-ca8a7f485806">

but if I directly encapsulate it into an mp4 file, and then type `. \ffprobe_vvceasy -i 1.mp4,` the content is wrong, from "15360x8640" to "45495x45495", and  the MP4 file cannot be extracted into a vvc file.
<img width="1269" alt="屏幕截图 2024-07-01 220501" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/8cddc588-2881-4cee-afc6-4ceabfb62848">

I even tried to use ffmpeg to directly convert the original video to mp4 with vvc encoding, but the result is also "45495x45495", I don't understand how to get this "45495"?

GitHub cannot upload vvc files directly, so I had to package it into a zip file
[1.zip](https://github.com/user-attachments/files/16054359/1.zip)

**Comment by adamjw24** [comment]
It seems to me the problem is in the muxer (or mp4 demuxer). VVdeC does correctly recognize the size if properly fed raw data.

What does the native ffmpeg VVC decoder think the size is in both cases?

**Comment by jiangzemin-xudamin** [comment]
@adamjw24 

[
<img width="1271" alt="屏幕截图 2024-07-05 212832" src="https://github.com/fraunhoferhhi/vvdec/assets/55375989/a5d4e755-a567-40e4-8676-a1d8f958ce65">
](url)

**Comment by adamjw24** [comment]
Interesting, strange, we'll have a look. Thanks

**Comment by lehmann-c** [comment]
Could you please specify how you created the mp4 file?

I tested the .vvc file with libvvdec and ffvvc - both fine
I generated  an mp4 with MP4Box (GPAC version 2.3-DEV-rev841-gb352e21fc-HEAD) and the mp4 also played fine with libvvdec and ffvvc without any issues.
I used following command:
MP4Box -add 1.vvc -new 1.mp4

**Comment by adamjw24** [comment]
It seems the problem is with the ffmpeg version you are using. The cross-check that you posted is based on a different version of ffmpeg, so its not really giving us any information.

It would be interesting to have an ffmpeg version with both ffvvc and vvdec included. If that version would show the error vvdec but not for ffvvc, it would be conclusive evidence that the problem is with vvdec.

For the, the resolution is as following:
- the problem is caused by an issue in an older version of ffmpeg
- please update to a newest ffmpeg version, as VVC support is very actively developed right now

**Comment by jiangzemin-xudamin** [comment]
@lehmann-c Same operation.

**Comment by jiangzemin-xudamin** [comment]
@adamjw24 Yes, the version is indeed old, probably the new version of ffmpeg fixes this bug.
