### ISSUE TITLE
macOS seg fault

### ISSUE THREAD

**Issue by witaly-iwanow** [fraunhoferhhi/vvdec#2]
So I was just starting to mess around with VVC enc and dec and got this crash right away. Encoded a raw I420 video with `vvencapp --preset faster -i video6.iyuv -s 360x360 -o video6.266 --framerate 10 --bitrate 125000` and then tried to decode it with `vvdecapp --bitstream video6.266 --output video6-dec.yuv` - got a crash in `void offsetBlock_SIMD<(X86_VEXT)4>(int, ClpRngTemplate<short> const&, int, int*, int, short const*, short*, long, long, int, int, bool, bool, bool, bool, bool, bool, bool, bool, std::__1::vector<signed char, std::__1::allocator<signed char> >*, std::__1::vector<signed char, std::__1::allocator<signed char> >*, bool, int*, int*, int, int)`.
`video6.266` and crash report attached.

[vvdec-crash.zip](https://github.com/fraunhoferhhi/vvdec/files/5192612/vvdec-crash.zip)

**Comment by adamjw24** [comment]
The problem has to do with unaligned SIMD loads in SAO implementation. Will be fixed in the next update. Thanks for reporting.
