### ISSUE TITLE
camke generated VS2022 project install incorrectly in MinSizeRel mode

### ISSUE THREAD

**Issue by meetviolet** [fraunhoferhhi/vvdec#201]
Hi, I found a wired install behavior when compile on win10 with VS2022 and cmake 3.28.1.

The camke-generated install procedure seems omit the library files in MinSizeRel mode, both `vvdec.lib` in static build and `vvdec.dll+vvdec.lib` in shared build.

The only fix I found is to mimic the install procedure manully, i.e., copy the vvdec.lib from `lib` directory, and vvdec.dll from `bin` directory by hand.

In other modes I've tested, i.e., `Debug`, `Release`, `RelWithDebInfo`, install goes fine. Only `MinSizeRel` mode didn't work.

I guess sth. went wrong in CMakeLists.txt?

By the way, vvenc also has this problem, see [this issue](https://github.com/fraunhoferhhi/vvenc/issues/432#issue-2580202344)

**Comment by K-os** [comment]
I'll look into it.
