### ISSUE TITLE
Please add 2 bool cmake entries for cmake-gui

### ISSUE THREAD

**Issue by meetviolet** [fraunhoferhhi/vvdec#202]
Hi, I think may be add these 2 entries for cmake-gui is better for users build from scratch.

BUILD_SHARED_LIBS: bool, for users who want static or shared builds.

BUILD_PROGRAMS: bool, for users who want library builds only.

**Comment by adamjw24** [comment]
BUILD_SHARED_LIBS is a CMake internal option, and should thus be exposed when you set the GUI to show external libraries. Please correct me if I'm wrong, I'm not using the gui.

vvdecapp is super lightweight so I don't think there is need to skip building it. It is not being installed anyways.

**Comment by meetviolet** [comment]
Actually, it's a common choice to put frequently used entries into cmake-gui, like `BUILD_SHARED_LIBS`, `BUILD_PROGRAMS`. Just for convenience.

Here is what entries `libfdk-aac` put in camke-gui by default. As shown below, `BUILD_SHARED_LIBS` and `BUILD_PROGRAMS` are added. 

![image](https://github.com/user-attachments/assets/e295f5a5-f84d-4284-8d8e-6f471cf859c8)
