### ISSUE TITLE
install-prefix is not working with ninja

### ISSUE THREAD

**Issue by MiKayule** [fraunhoferhhi/vvdec#212]
I'm trying to build an ffmpeg with vvdec, vvenc integrated by a script for Mac. According to the Wiki, I should use a building command like this:

`make g=ninja install install-prefix=/path/to/install/dir`

but it seems that the `install-prefix` is not working completely, no matter what the `/path/to/install/dir` is, it was always installed to /path/to/source/install/ instead.

Without `g=ninja`, or compiling with Xcode, it works if I run it by hand, but still doesn't work within a script (which means it will be installed to the source directory).

I added a manual copy command after the compilation and installation of vvdec (`cp -r install/* $TOOL_DIR/`), then the whole compiling process works fine.

The same issue also exists in vvenc

#### my building script for ffmpeg (partial):
```bash
# build
make g=ninja -j $CPUS release-shared
checkStatus $? "build failed"

# install
make g=ninja install install-prefix=$TOOL_DIR
checkStatus $? "installation failed"
```
#### clang -v
```
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
#### uname -a
`Darwin MiKaMac.lan 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031 arm64`
#### ninja --version
`1.12.1`

**Comment by adamjw24** [comment]
Hi,

because of how the makefile is only the prefix to the CMake, you have to provide the install prefix with the first make call.

I.e.

```sh
# clean
make clean # delete build dir

# build
make g=ninja -j $CPUS release-shared install-prefix=$TOOL_DIR # setup the CMake build directories - need to set all CMake variable here
checkStatus $? "build failed"

# install
make install # call the install target in the previously setup CMake build tree
checkStatus $? "installation failed"
```

**Comment by MiKayule** [comment]
Oh, that's helpful. Sorry that I'm not good at CMake and Makefiles. Thank you so much!

**Comment by MiKayule** [comment]
@adamjw24 It seems that `make install` will let CMake reconfigure it for Xcode, recompile it with Xcode, and install that Xcode one instead of the one compiled by Ninja before. Maybe all variables must be set for both make calls.
I.e.
```bash
make g=ninja -j $CPUS release-shared install-prefix=$TOOL_DIR
make g=ninja -j $CPUS install install-prefix=$TOOL_DIR
```

I think that calling CMake directly may be a better idea if I want to do compilation and installation process separately.
I.e.
```bash
# prepare build
cmake -S . -B build/release-shared -G 'Ninja' -DCMAKE_INSTALL_PREFIX=$TOOL_DIR -DCMAKE_BUILD_TYPE=Release

# build
cmake --build build/release-shared -j $CPUS
checkStatus $? "build failed"

# install
cmake --build build/release-shared --target install
checkStatus $? "installation failed"
```

**Comment by K-os** [comment]
Yes, if you do want to do any customization for your build, it makes sense to call cmake directly. Then you do have more control over the actual build steps. The top level Makefile is more a convenience wrapper.
