### ISSUE TITLE
Implicit Downcasting of Exceptions by operator<<

### ISSUE THREAD

**Issue by Xosrov** [fraunhoferhhi/vvdec#213]
The [operator<<](https://github.com/fraunhoferhhi/vvdec/blob/31d0e257a1e21a0044ed19c7f7ce3f1e6609c4ca/source/Lib/CommonLib/TypeDef.h#L747) implementation of the `Exception` type forcefully downcasts all inherited class types when the operator is used. A problematic usecase is in `THROW_RECOVERABLE`, that is used by the [`CHECK`](https://github.com/fraunhoferhhi/vvdec/blob/31d0e257a1e21a0044ed19c7f7ce3f1e6609c4ca/source/Lib/CommonLib/TypeDef.h#L822) macro.
Basically all exceptions thrown by `CHECK` are irrecoverable at the moment. An easy fix would be to replace all `THROW_*` variants with something like:
```C++
#define THROW_RECOVERABLE(msg)                           \
    do                                                   \
    {                                                    \
        std::ostringstream oss;                          \
        oss << "\nERROR: " << FMT_ERROR_LOCATION << msg; \
        throw RecoverableException(oss.str());           \
    } while (0)
```

**Comment by Xosrov** [comment]
[Short demonstration](https://godbolt.org/z/sqf1K3TG3), hope I was clear in my description.

**Comment by K-os** [comment]
Oh, thanks. Good catch!

There used to be an overload for the `operator<<` for each derived Exception class, but I must have accidentally deleted it during a code cleanup. I'll add it back into the code.
