### ISSUE TITLE
Uninitialized Variables in ARM7l Build

### ISSUE THREAD

**Issue by Xosrov** [fraunhoferhhi/vvdec#216]
I'm testing on a armv7l (32bit) system within docker to build vvdec, here is the output of `uname -a`:  
`Linux d9f643bbff1e 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 armv7l armv7l armv7l GNU/Linux`  

The release build fails because of uninitialized variables. Ignoring these errors does cause segfaults when decoding some VVC samples. I'm using the latest release `v3.0.0`.
```bash
In file included from /app/vvdec/source/Lib/CommonLib/x86/sse41/IntraPred_sse41.cpp:43:
/app/vvdec/source/Lib/CommonLib/x86/sse41/../IntraPredX86.h: In function ‘void vvdec::IntraPredAngleCore_SIMD(int16_t*, ptrdiff_t, int16_t*, int, int, int, int, const TFilterCoeff*, bool, const ClpRng&) [with vvdec::x86_simd::X86_VEXT vext = vvdec::x86_simd::SSE41; int W = 8]’:
/app/vvdec/source/Lib/CommonLib/x86/sse41/../IntraPredX86.h:309:22: error: ‘vbdmax’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  309 |       __m128i vbdmin,vbdmax;
      |                      ^~~~~~
```

Let me know if you need assistance setting up the build environment. Thank you!

**Comment by Xosrov** [comment]
By the way the uninitialized variables are causing the build to fail. I tried to ignore the warning but the uninitialized variable(s) cause segfaults when decoding some samples.

**Comment by adamjw24** [comment]
The variables are initialized alright, your compiler is over-sensitive.

Please try compiling setting either `enable-werror=0` for make or `-DVVDEC_ENABLE_WERROR=0`.

Would be great if you could share the bitstream, so we can see where the segfailts are actually coming form.

**Comment by adamjw24** [comment]
There might also be an issue with the armv7, which is causing the issues. We'll investigate it a bit.

**Comment by adamjw24** [comment]
I merged your pull request, thank you. Does this mean we can now set ARMv7 as working the README.md? Could you confirm than quick?

**Comment by Xosrov** [comment]
Thank you for the quick response! We can close this since uninitialized variables weren't causing the issue
