### ISSUE TITLE
Valgrind Uninitialized Memroy Issues

### ISSUE THREAD

**Issue by Xosrov** [fraunhoferhhi/vvdec#222]
There are a lot of Valgrind issues relating to the use of uninitialised memory and conditional jumps depending on them. Obviously a lot of this is unimportant since it doesn't make sense to initialize every bit of memory.
Is it safe to ignore all of such report from VVDeC, or is there a valgrind suppressions file somewhere? I'd be happy to help reporting and classifying them if necessary. 

Best regards.

**Comment by adamjw24** [comment]
Please have a look at: https://github.com/fraunhoferhhi/vvdec/blob/192baa18cb8ded1786d1ff343eba63854f3e3bbf/source/Lib/CommonLib/TypeDef.h#L102

We identified a lot of false positives, and to check the code with Valgrind, we a use more memsets. For each of this memsets, we analyzed it and are quite sure those are false positives, thus don't need to be initialized in production code. Still, let me know if you disagree with any of the instances, or if you find unitialized memory issues even with this code enabled.

**Comment by Xosrov** [comment]
Thank you Adam :). Setting it fixes the issue at least so far. If there are still issues I will re-open the ticket
