### ISSUE TITLE
VVDEC Pipe output not supported

### ISSUE THREAD

**Issue by baxxtor** [fraunhoferhhi/vvdec#29]
It appears vvdec does not support pipe output using -o - or any other command option.  Unfortunately, YUV files are enormous.  It would be very efficient if vvdes could output via pipe into vlc or mplayer for testing purposes.

Would you please plan that in next version?

Any help would be greatly appreciated.  Thank You.

**Comment by K-os** [comment]
Thanks for the suggestion. That should be pretty easy to implement. We'll look into that for the next version.
If you are on Linux or MacOS, you can just use named pipes as a workaround:

Create a named pipe and use it as input for your next step (e.g. gzip):
```
mkfifo yuv_pipe
cat yuv_pipe | gzip - >out.yuv.gz &
```
Use the named pipe as output for vvdec:
```
./bin/release-static/vvdecapp -b input.bit -o yuv_pipe
```

On Windows the concept of named pipes exists also, but I don't know how to create them from the command line and if they are actually accessible as files.

**Comment by 1480c1** [comment]
> On Windows the concept of named pipes exists also, but I don't know how to create them from the command line and if they are actually accessible as files.

Named pipes are not accessible through the command line and you will need to compile your own program to make one or somehow try to do so through powershell and C#

**Comment by K-os** [comment]
> Named pipes are not accessible through the command line and you will need to compile your own program to make one or somehow try to do so through powershell and C#

Ah, ok. Thanks for the info.

**Comment by baxxtor** [comment]
I believe I may have used to wrong term.  Instead of a named pipe, I was hoping stdin and stdout support could be implement in a future release of vvdec and vvenc.  Essentially you could create take vvcdec or vvcenc and stdout ir stdin into another application.  For example: vvdec -b bitstream.file -o - | vlc -

Hopefully, this clarifies the feature request.

Thank You.

**Comment by K-os** [comment]
Yes, I understood that you suggested std-out support. My suggestion was just a workaround how to get the same effect without the support implemented in the decoder.
If you run `cat` on the named pipe, you will basically get the YUV output on stdout.

**Comment by baxxtor** [comment]
K-os,

Thank you that worked and was very helpful.  One other question, how would you perform the opposite with vvenc?  Basically how would you take an application such as ffmpeg and feed its output to a named pipe that vvenc would accept?

I attempted this without success

mkfife outpipe

./ffmpeg -i input.mp4 "output parameters to convert to mp4 yuv / rawvideo such as framerate, yuv420p, video size, etc." pipe:1 > outpipe

vvencapp -i outpipe "all other necessary parameters such as size, preset, framerate, etc." -o out.vvc

Unfortunately, vvencapp reads the pipe and then just quits with zero frames encoded.

Thank you for your help.

**Comment by K-os** [comment]
You're welcome.

I am not sure if you can use the same workaround for vvenc and I have not tested it. Two-pass rate control will definitely not work the way it is currently implemented, because it needs to read the file twice, which naturally does not work with pipes. That might be the reason why you got it running with the vvencFFapp, but not the simpler one: maybe you used a config with single-pass rate control with the FF-app.

**Comment by lvaschmidt** [comment]
Is this in progress already or maybe looking for a contributor?

**Comment by baxxtor** [comment]
Hello,

This feature is looking for a contributor.  Currently, I cobbled a bunch of
BASH scripts and named pipes to 'pipe' vvenc and vvdec into other
applications.

Thank You,

**Comment by adamjw24** [comment]
This issue is also already in progress. We will have it ready by next week.

**Comment by baxxtor** [comment]
Adam,

Thank you for the update.  It is much appreciated and I look forward to the
new feature!

**Comment by adamjw24** [comment]
Fixed in #49

**Comment by lp200** [comment]
Pipe output on windows is probably broken.
The file size was different from the normal output.

vvdecapp -b test.266 -o - > pipe.yuv
pipe.yuv 720,972,850

vvdecapp -b test.266 -o test.yuv
test.yuv 718,848,000 


I tried both commands on ubuntu and it worked fine.
Both were the same file size as test.yuv

**Comment by 1480c1** [comment]
Which shell did you use to run those commands?

**Comment by baxxtor** [comment]
Confirmed it's broke on Windows but works on Centos.  The stdout data is
all scrambled on Windows.
