### ISSUE TITLE
Installs files into the source directory

### ISSUE THREAD

**Issue by yurivict** [fraunhoferhhi/vvdec#3]
I've built it in /usr/ports/multimedia/vvdec/work and the installed files list looks like this:
```
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/bin/%%CMAKE_BUILD_TYPE%%-static/vvdecapp
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/include/vvdec/version.h
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/include/vvdec/vvdec.h
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/include/vvdec/vvdecDecl.h
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/lib/cmake/VVDec/VVDecConfig.cmake
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/lib/cmake/VVDec/VVDecConfigVersion.cmake
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/lib/cmake/VVDec/static/VVDecTargets-%%CMAKE_BUILD_TYPE%%.cmake
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/lib/cmake/VVDec/static/VVDecTargets.cmake
/usr/ports/multimedia/vvdec/work/vvdec-df4be18/install/lib/%%CMAKE_BUILD_TYPE%%-static/libvvdec.a
```

The cmake ```install``` instructions should simply have targets like "include", "lib".

**Comment by 1480c1** [comment]
it would probably help if they just use the GNUInstallDirs as well

**Comment by yurivict** [comment]
There is no need to try to build both Debug and Release targets in cmake, cmake isn't designed this way.

The target type should be passed to cmake through its standard variable ```CMAKE_BUILD_TYPE```, see https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html

In case you need to build for multiple target types, an external script should invoke cmake with different ```CMAKE_BUILD_TYPE``` values.

**Comment by adamjw24** [comment]
Thanks for pointing that out. We see the problem. For now the build process was optimized for development and multi-target testing, but of course for deployment it doesn't make sense. We'll adapt it in the next update.
