### ISSUE TITLE
vvdec compile problem under Windows

### ISSUE THREAD

**Issue by pigpeppa** [fraunhoferhhi/vvdec#35]
It looks like vvdec is using pthread under windows. How can i get pthread support under Windows? b.t.w. I am using vs2015.

**Comment by adamjw24** [comment]
The pthread dependency is guarded by the __linux macro and only used to set thread name. This should not be active in MSVC. All of the actual threading is done with C++ and std::thread.

What is the exact error you're having?

**Comment by Provissy** [comment]
Tested with VS 2019, no error occured

```
cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release --parallel 8
```

Try update your cmake or MSVC ?

**Comment by adamjw24** [comment]
Closing since inactive
