### ISSUE TITLE
v1.0.0.0 decode POUT_A_Sharplabs_2.bit failed

### ISSUE THREAD

**Issue by chenm001** [fraunhoferhhi/vvdec#40]
I report this issue in discussions page, and I just confirm it is a bug this morning.

In the latest v1.0.0.0 code, we will get decoded output YUV hash check failed on sequence POUT_A_Sharplabs_2.bit.
The root cause is the sequence POUT_A_Sharplabs_2.bit active **ph_pic_output_flag** for bypass some of output frames.
However, in the source code, the below code was disabled for unknown reasons since v1.0.0.0 release.
`pcPic->neededForOutput = (pcSlice->getPicHeader()->getPicOutputFlag() ? true : false);`

**Comment by adamjw24** [comment]
Thanks for finding the issue. There were some problems with the derivation of the flag regarding tuning in and GDR. We plan on doing the cleanup of the management of this flag soon, hopefully it will resolve the issue.

**Comment by adamjw24** [comment]
fixed in #49
