### ISSUE TITLE
STDOUT on Windows not functioning 

### ISSUE THREAD

**Issue by baxxtor** [fraunhoferhhi/vvdec#51]
Stdout on Windows is not functioning.  Although stdout ir outputting data, the data is is in some format that the video is not useable.  However, STDOUT data on Centos appears to working as expected.

**Comment by 1480c1** [comment]
to the developers, it might be worth it to look into https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-160 and seeing if you need to set O_BINARY on the stdout, same with stdin for vvencc

**Comment by baxxtor** [comment]
You may have a point.  Perhaps Windows by default is outputting stdin /
stdout as text instead of binary.

**Comment by baxxtor** [comment]
Developers, this article may also be of interest to you:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/text-and-binary-mode-file-i-o?view=msvc-160

**Comment by baxxtor** [comment]
I can confirm the stdout fix is working on Windows.  Thank You.

**Comment by adamjw24** [comment]
Seems fixed for Windows. Problems reported under PowerShell, but works with cmd.exe.
