### ISSUE TITLE
Compiling warning

### ISSUE THREAD

**Issue by NicolasProy** [fraunhoferhhi/vvdec#56]
Hi!

While compiling VVdeC with Visual Studio 2017 I've stumbled accross this warning for lines 430, 433, 435 and 438 of the "adaptiveloopfilterx86.h" file:
\vvdec-master\vvdec-master\source\lib\commonlib\x86\adaptiveloopfilterx86.h(438): warning C4789: buffer ' ' of size 8 bytes will be overrun; 32 bytes will be written starting at offset 0.
Is this a normal behavior, can I safely ignore those warnings? 

Thanks in advance,
Nicolas.

**Comment by NicolasProy** [comment]
Thank you for your quick answer, 

I tried compiling version 1.1.1, and I am pretty sure I had the same issue with the previous version.
My msvc version is 15.5.4

I ignored the warning while compiling the last times I compiled and it didn't seem to cause any problem, but I wanted to be sure by reporting the issue.

Nicolas

**Comment by adamjw24** [comment]
Hmm, mine is 15.9.26. If the warning goes away towards higher version thats a good sign I guess.

I think there is no issue there, also bcs its actually part of the code thats used a lot - if there was a problem, it should show during runtime.

Ignoring it sounds good for now. I'll have more in-depth look there one of those days.

**Comment by NicolasProy** [comment]
Okay, thanks a lot for your answers.
