### ISSUE TITLE
Add riscv64 to supported architectures

### ISSUE THREAD

**Issue by pkubaj** [fraunhoferhhi/vvdec#77]
Tested to work fine on FreeBSD. I'm not sending a PR, because FreeBSD is not in the table, but I suspect it should work fine on Linux as well.

**Comment by K-os** [comment]
Same as with PowerPC. See #76

**Comment by adamjw24** [comment]
Same as my comment on #76. What are some current riscv64 CPUs and systems? Are those powerful enough to run at least like 1080p60 VVC decoding?

**Comment by pkubaj** [comment]
Currently the best publicly available board is https://www.sifive.com/boards/hifive-unmatched. I'm not sure about its performance, since I don't have one.
I have the BeagleV developer beta (https://beagleboard.org/static/beagleV/beagleV.html). It's much slower and has some issues with display, so I can't really test vvdec. I think it MAY not be fast enough. But RISC-V is a pretty young architecture and it's rapidly developed, so I think it would be nice to have as much supported as possible.

**Comment by adamjw24** [comment]
Added to Wiki: https://github.com/fraunhoferhhi/vvdec/wiki

We'll not have official support, but will allow the simd-e to be used with whatever is detected. Will be fixed in an PR soon.

**Comment by pkubaj** [comment]
Per, https://github.com/simd-everywhere/simde/blob/master/simde/simde-arch.h, it looks like there are a lot more supported architectures than README states.

**Comment by adamjw24** [comment]
I get it. Its just about we can only support archs we can test with. You're free to do your own tests and use the project in whatever way you want.

**Comment by K-os** [comment]
@pkubaj can you please give #81 a try on RiscV64 also? 

Compilation with GCC failed on Linux because of linker errors (undefined reference to __atomic_compare_exchange_1 and __atomic_exchange_1) even with -latomic. But that seems to be a GCC problem, since you were successful with clang.

**Comment by pkubaj** [comment]
OK on riscv64.
