### ISSUE TITLE
CMake error at Path

### ISSUE THREAD

**Issue by asqarkababi** [fraunhoferhhi/vvdec#79]
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/mmard/source/repos/vvdec/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_d3696 && [1/2] Building C object CMakeFiles\cmTC_d3696.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_d3696.exe
    FAILED: cmTC_d3696.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_d3696.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_d3696.dir\testCCompiler.c.obj  /out:cmTC_d3696.exe /implib:cmTC_d3696.lib /pdb:cmTC_d3696.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_d3696.dir/manifest.res CMakeFiles\cmTC_d3696.dir/manifest.rc" failed (exit code 0) with the following output:
    Das System kann die angegebene Datei nicht finden
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake	66	
Hello How to solve this ?

**Comment by adamjw24** [comment]
Could you please paste a full log of what it is you're doing?

Do you open a project through "Open CMake dir" or generate it with `make configure` or `cmake ...` or the CMakeGUI?

Looks like a broken MSVC installation, but cannot be sure without more info.

**Comment by asqarkababi** [comment]
I installed CMake on Visual Studio 2019 Community and Cloned the Git Repository 
Im using the Paper to install the vvdec step by step when i open the folder with the project i even cant debug like vvenc 
I get the following error in the error list  
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/mmard/OneDrive/Desktop/vvdec-1.2.0-1/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_34e6f && [1/2] Building C object CMakeFiles\cmTC_34e6f.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_34e6f.exe
    FAILED: cmTC_34e6f.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_34e6f.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_34e6f.dir\testCCompiler.c.obj  /out:cmTC_34e6f.exe /implib:cmTC_34e6f.lib /pdb:cmTC_34e6f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_34e6f.dir/manifest.res CMakeFiles\cmTC_34e6f.dir/manifest.rc" failed (exit code 0) with the following output:
    Das System kann die angegebene Datei nicht finden
    ninja: build stopped: subcommand failed.  CMake will not be able to correctly generate this project.		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake	66	
<img width="960" alt="Screenshot 2022-02-20 175045" src="https://user-images.githubusercontent.com/96051597/154854068-964b3551-ea32-44a3-8813-63f855ece9f8.png">

**Comment by adamjw24** [comment]
The problem is, you're build fails before it actually starts processing VVdeC, it fails at checking your environment, which makes it hard for me to understand.

Can you download some sample C++ project (I'm sure MSVC or CMake have stuff like that) and see if you can build it?

Otherwise, I see you checked out the project to OneDrive, which as I understand is cloud storage, right? Maybe try cloning properly to local hard-disk?

Last but not least, please use the latest version of VVdeC.

**Comment by asqarkababi** [comment]
I build vvenc before just fine without any problems with the last builing i will try vvdec again this time with cloning it again

**Comment by adamjw24** [comment]
Strange. I'll ask around if someone has seen this problem. What if you do it from the console?

```cmd
# git clone ...
# cd vvdec
# make distclean
# make install-release
```

**Comment by asqarkababi** [comment]
make functions dont work on th VS Console because of the Cmake problem

**Comment by lehmann-c** [comment]
If you want to use make/Makefiles on Windows be sure to install gnuwin32.
Please have a look into the wiki to see how you can build via make or via cmake:
[https://github.com/fraunhoferhhi/vvdec/wiki/Build](url)

You can also build with cmake by using e.g.:
cmake -S . -B build/static -A x64 -DCMAKE_CONFIGURATION_TYPES=Release
cmake --build build/static --config Release  -- /maxcpucount:8 /verbosity:minimal /nr:false

**Comment by asqarkababi** [comment]
> If you want to use make/Makefiles on Windows be sure to install gnuwin32. Please have a look into the wiki to see how you can build via make or via cmake: [https://github.com/fraunhoferhhi/vvdec/wiki/Build](url)
> 
> You can also build with cmake by using e.g.: cmake -S . -B build/static -A x64 -DCMAKE_CONFIGURATION_TYPES=Release cmake --build build/static --config Release -- /maxcpucount:8 /verbosity:minimal /nr:false

Thank you very much i installed mingw32 and in the commandline in VSS2019 i wrote instead of make mingw32-make install-release and it worked i decoded a video to yuv and watched the video on yuvplayer but it looks like this  and its very small
<img width="175" alt="Screenshot 2022-02-21 100848" src="https://user-images.githubusercontent.com/96051597/154923349-2247abe8-e242-4d49-b9b1-3e095f1abadc.png">

**Comment by adamjw24** [comment]
About how the video looks, did you have a look at? https://github.com/fraunhoferhhi/vvdec/discussions/50

**Comment by asqarkababi** [comment]
Could you give me a hint how to decode it properly i encoded it with the simple app and not with the professional app is there a difference between their results ? is it possible to decode the encoded file with the simple app with vdecapp ?

**Comment by adamjw24** [comment]
You probably decoded it properly, you just need to view it properly now. Your format is yuv420p10le, and not yuv420p.

Could you do a list of the steps you did (exact command lines) as well as list the files and files sizes of all used files (input, bitstream, reconstruction).

**Comment by adamjw24** [comment]
This will not work. You cannot feed an mp4-file to VVenC. You could for example use the following script to transcode an mp4-file to .266: https://github.com/fraunhoferhhi/vvenc/discussions/116

Alternatively, decode the mp4 to a YUV using: `ffmpeg -i R.mp4 -f rawvideo -pix_fmt yuv420p10le R.yuv`

Than, repeat the process using `-i R.yuv` instead of `-i R.mp4` in the VVenC command-line.

**Comment by asqarkababi** [comment]
Thank you very much i will try it out and report you the outcome

**Comment by adamjw24** [comment]
Wait, no. If you convert mp4 to yuv as yuv420p10le, you have to use `-c yuv420_10`. So:
`vvencapp -i R.yuv -s 1920x1080 -c yuv420_10 -r 30 --preset medium --qp 31 --qpa 0 -ip 64 -t 4 -o R.266`

**Comment by asqarkababi** [comment]
I converted the mp4 file to yuv file but vlc player doesnt play it even in the documentation of VLC it ia compatible with it

**Comment by adamjw24** [comment]
And ffplay?
`ffplay -f rawvideo -pix_fmt yuv420p10le -i R.yuv`

I'm not an expert on VLC so don't know how to make it play.

**Comment by adamjw24** [comment]
Why don't you just use YUView or other yuvplayer to play the yuv?

**Comment by asqarkababi** [comment]
> And ffplay? `ffplay -f rawvideo -pix_fmt yuv420p10le -i R.yuv`
> 
> I'm not an expert on VLC so don't know how to make it play.

I will try the command 


> Why don't you just use YUView or other yuvplayer to play the yuv?
<img width="176" alt="Screenshot 2022-02-21 141736" src="https://user-images.githubusercontent.com/96051597/154962990-a56b7d17-e5bb-40c5-be36-c01dce9e76b3.png">

I used yuvplayer and i got that pixelated output i will try YUVIEW too to see how the result is

**Comment by adamjw24** [comment]
Change the input format of your yuvplayer from 8 to 10 bit

**Comment by adamjw24** [comment]
Or maybe actually more simply, use an 8-bit pipeline:
Convert `R.mp4` to `R.yuv`: `ffmpeg -i R.mp4 -f rawvideo -pix_fmt yuv420p R.yuv`
Encode with VVenC, 8-bit:  `vvencapp -i R.yuv -s 1920x1080 -c yuv420 -r 30 --preset medium --qp 31 --qpa 0 -ip 64 -t 4 --internal-bitdepth 8 -o R.266`
Decode with VVdeC: `vvdecapp -b R.266 -o R2.yuv`

Now both `R.yuv` and `R2.yuv` are 8-bit YUVs. I think this would be more suited for your testing.

**Comment by asqarkababi** [comment]
I tried it out video is not playing no pixelation anymore
<img width="953" alt="Screenshot 2022-02-21 150008" src="https://user-images.githubusercontent.com/96051597/154969514-45dbcc7c-77a7-4f32-8240-b7e3558d6bcc.png">

**Comment by adamjw24** [comment]
With the 8-bit pipeline you should be able to just use yuvplayer.

**Comment by asqarkababi** [comment]
> With the 8-bit pipeline you should be able to just use yuvplayer.
<img width="183" alt="Screenshot 2022-02-21 150514" src="https://user-images.githubusercontent.com/96051597/154970437-81051605-faf6-4ea6-95b3-40325e0ecf78.png">

Strange its still pixelated

**Comment by adamjw24** [comment]
I don't know than. For YUView you have to set the correct size in the right pane. I don't know what yuvplayer is. Did you set the correct video size? yuv is a format that does not contain any metadata whatsoever (no width/height, nothing), so you have to tell your player explicitly how to interpret this.

Please make sure you can actually view your raw YUV input properly before we continue discussing usage of VVenC and VVdeC.

**Comment by asqarkababi** [comment]
Thank you very much for your help i will try to figure it out why its still pixelated as a beginner is an nice adventure

**Comment by adamjw24** [comment]
Your source it what it is. Just set the proper resolution while encoding (`-s 540x360`).

**Comment by asqarkababi** [comment]
> Your source it what it is. Just set the proper resolution while encoding (`-s 540x360`).

Thank you very much

**Comment by asqarkababi** [comment]
it seems both encoder and decoder work properly 
I thank you so much for your help 
I close this issue now
