### ISSUE TITLE
Decoding vvc files despite corruption

### ISSUE THREAD

**Issue by elhachi** [fraunhoferhhi/vvdec#83]
Hello,

I have a corrupted VVC binary file and I want to decode it using the vvdec application, but it gave me the following error:
vvdecapp [error]: decoding failed:  (decoder requires restart) detail: caught unknown exception
ERROR: In function "void vvdec::DecSlice::parseSlice(vvdec::Slice*, vvdec::InputBitstream*, int)" in /home/labiod/vvdec/source/Lib/DecoderLib/DecSlice.cpp:172: Expecting a terminating bit
ERROR CONDITION: !binVal
I tried to decode it using VTM also, but it gave me:
ERROR: In function "decompressSlice" in /home/XXXX/VVCSoftware_VTM/source/Lib/DecoderLib/DecSlice.cpp:250: Expecting a terminating bit

Please let me know if there is a way to decode VVC files despite the corruption.

**Comment by adamjw24** [comment]
Error resilience is still on the roadmap, we'll look into that. Technically you could just keep feeding the decoder the frames, and starting at the next random access point it should restart providing correct decoded frames (please mind that the way vvdecapp talks to the library does not support that use case, and we'll have to check if the lib would even behave correctly).

I'll leave this open until we implemented some error resilience.
