### ISSUE TITLE
MacOS arm64 shared build

### ISSUE THREAD

**Issue by adamjw24** [fraunhoferhhi/vvdec#89]
After compiling a shared build for arm64 under MacOS using default settings, the apps linking against libvvdec fail at start with SigKill (9).

**Comment by adamjw24** [comment]
For now, the cause of the issue is unknown, but somehow connected to Xcode. Building under MacOS without Xcode helps.

For `make`-based build, please use `g=ninja` or `g=umake` to select an alternative generator. For CMake, select 'Ninja' or 'Unix Makefiles' as the generator to bypass Xcode.

**Comment by K-os** [comment]
I just built the latest revision from master (e83c1166) on ARM64 Mac and the test suite completed successfully. I think we can close this issue.

**Comment by K-os** [comment]
I just noticed: the build output actually tells us what goes wrong during the install step:
```
-- Installing: /Users/hege/projects/vvdec/install/lib/libvvdec.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/hege/projects/vvdec/install/lib/libvvdec.dylib
-- Installing: /Users/hege/projects/vvdec/install/bin/vvdecapp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/hege/projects/vvdec/install/bin/vvdecapp
```

This is most probably due to the RPATH being updated during the install step.
