### ISSUE TITLE
Looping in FFplay

### ISSUE THREAD

**Issue by scenarnick** [fraunhoferhhi/vvdec#99]
Using libvvdec (master) in FFmpeg / ffplay from this fork: https://github.com/tbiat/FFmpeg/releases/tag/vvc (master)

When trying to loop a simple video (VVC in MP4) I get this error on hitting the loop point: 

```
[libvvdec @ 0x15083f400] error in vvdec::decode - ret:-11 - decoder already flushed, please reinit.
    Last message repeated 271 times
[libvvdec @ 0x15083f400] Too many errors when draining, this is a bug. Stop draining and force EOF.

```
Looping with HEVC and AVC payload works correctly.

**Comment by adamjw24** [comment]
> Using libvvdec (master) in FFmpeg / ffplay from this fork: https://github.com/tbiat/FFmpeg/releases/tag/vvc (master)

So are you using the master or the tag? As far as I know, the tag had some problems, that were fixed in the master, so maybe try the newest master?

**Comment by scenarnick** [comment]
Sorry for confusion - I was using the tag. Building master now. Will report back

**Comment by scenarnick** [comment]
Issue no longer reproducible in Master of https://github.com/tbiat/FFmpeg. Thanks for the hint - issue closed.
